name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout git branch
      uses: actions/checkout@v3

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_SECRET_KEY }}'
        # token_format: access_token
        # workload_identity_provider: <your-provider-id>
        # service_account: youtube-data-project@wide-hexagon-397214.iam.gserviceaccount.com
        # access_token_lifetime: 300s

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: asia-south1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    
    - name: Build the Docker image
      run: make docker-build
      
    - name: Push the docker image
      run: make docker-push
